#! /bin/sh

# autostart polybar
# $HOME/.config/polybar/launch.sh &

# lockscreen with lid closed
xss-lock --transfer-sleep-lock -- i3lock --nofork &

# bspwm settings
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &
bspc config window_gap 5
bspc config border_width 2
bspc config normal_border_color "#7B6E63"
bspc config focused_border_color "#A9B665"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
