#!/bin/sh

# autokill
pkill -9 -x sxhkd
pkill -9 polybar
pkill -9 feh
pkill -9 dunst
pkill -9 gammastep
pkill -9 polkit-mate-authentication-agent-1

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
polybar top &
feh -pq --bg-fill --no-fehbg ~/.config/bg/pacman.png &
dunst &
gammastep -P -x -r -O 2300 &
/usr/libexec/polkit-mate-authentication-agent-1 &
xrdb -merge ~/.Xresources

# lockscreen with suspend
xss-lock --transfer-sleep-lock -- i3lock --nofork --radius 50 --inside-color=00000000 --line-uses-inside --verif-size=16 --verif-text="Verifying" --wrong-size=16 --wrong-text="Wrong" -Fei ~/.config/bg/lock.png &

# tty-like keyboard rate
xset r rate 300 50

# general
bspc monitor -d 1 2 3 4 5 6 7 8 9 &
bspc config window_gap 5
bspc config border_width 2
bspc config normal_border_color "#7B6E63"
bspc config focused_border_color "#98971A"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bsp-layout set tall 1 -- --master-size 0.5
bsp-layout set tall 2 -- --master-size 0.5
bsp-layout set tall 3 -- --master-size 0.5
bsp-layout set tall 4 -- --master-size 0.5
bsp-layout set tall 5 -- --master-size 0.5
bsp-layout set tall 6 -- --master-size 0.5
bsp-layout set tall 7 -- --master-size 0.5
bsp-layout set tall 8 -- --master-size 0.5
bsp-layout set tall 9 -- --master-size 0.5

# float rule
bspc rule -a pavucontrol state=floating
bspc rule -a ffplay state=floating
