#!/bin/sh

draw() {
  path="$(readlink -f -- "$1" | sed 's/\\/\\\\/g;s/"/\\"/g')"
  printf '{"action":"add","identifier":"preview","x":%d,"y":%d,"width":%d,"height":%d,"scaler":"contain","scaling_position_x":0.5,"scaling_position_y":0.5,"path":"%s"}\n' \
    "$x" "$y" "$width" "$height" "$path" >"$FIFO_UEBERZUG"
  exit 1
}

hash() {
  cache="$HOME/.cache/lf/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f -- "$1")" | sha256sum | cut -d' ' -f1).jpg"
}

cache() {
  if ! [ -f "$cache" ]; then
    dir="$(dirname -- "$cache")"
    [ -d "$dir" ] || mkdir -p -- "$dir"
    "$@"
  fi
  draw "$cache"
}

file="$1"
width="$2"
height="$3"
x="$4"
y="$5"

case "$(file --dereference --brief --mime-type -- "$1")" in
	image/*)
		if [ -p "$FIFO_UEBERZUG" ]; then
			orientation="$(magick identify -format '%[orientation]\n' -- "$1[0]")"

		if [ -n "$orientation" ] \
		&& [ "$orientation" != Undefined ] \
		&& [ "$orientation" != TopLeft ]; then
			hash "$file"

			cache magick -- "$1[0]" -auto-orient "$cache"
		else
			draw "$1"
		fi
		fi ;;

	video/*)
		if [ -p "$FIFO_UEBERZUG" ]; then
			hash "$1"
			cache ffmpegthumbnailer -i "$1" -o "$cache" -s 0
		fi ;;

	text/*)
		bat --color=always -pp "$1";;

	image/*)
		image "$2" "$3" "$4" "$5" "$1" ;;

	text/* | */xml | application/json | application/x-ndjson)
		bat -p --theme ansi --terminal-width "$(($4-2))" -f "$1" ;;

	audio/* | application/octet-stream)
		exiftool "$1" ;;

	video/* )
		CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
		[ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
		image "$CACHE" "$2" "$3" "$4" "$5" "$1"	;;

	*/pdf)
		pdftotext -l 5 -nopgbrk -layout -q -- "$1" - ;;

	application/*zip)
		atool -l -- "$1" ;;

	*opendocument*)
		odt2txt "$1" ;;

esac
exit 0
