#!/bin/sh

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

case "$(file --dereference --brief --mime-type -- "$1")" in
	text/troff) man ./ "$1" | col -b ;;
	text/*|*/xml|application/json|application/x-ndjson) bat -p --theme ansi --terminal-width "$(($4-2))" -f "$1" ;;
	audio/*|application/octet-stream) mediainfo "$1" || exit 1 ;;
	application/*zip) atool --list -- "$1" ;;
	application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
