import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

[font]
size = 6

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[window.padding]
x = 1
y = 1

[colors]
draw_bold_text_with_bright_colors = false
