import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 8

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window.class]
general = "alacritty"
instance = "alacritty"

[window.padding]
x = 1
y = 1
