#!/bin/sh

# autokill
pkill -9 swayidle
pkill -9 waybar
pkill -9 swaybg
pkill -9 dunst
pkill -9 gammastep

# autostart
waybar &
swaybg -m fill -i ~/.config/bg/pacman.png &
mpd --no-daemon ~/.config/mpd/mpd.conf &
dunst &
gammastep -Pxr -O 2300 &
/usr/libexec/polkit-mate-authentication-agent-1 &

# lockscreen with suspend
riverctl map-switch normal lid open spawn 'swaylock --indicator-thickness 7 --inside-color 00000000 --font-size 16 -nes fill -i ~/.config/bg/lock.png'

# tty-like keyboard config
riverctl set-repeat 50 300

# tearfree support
riverctl allow-tearing disabled

# xorg-like idle
swayidle -w \
  timeout 600 'swaylock --indicator-thickness 7 --inside-color 00000000 --font-size 16 -fnes fill -i ~/.config/bg/lock.png' \
  timeout 600 'wlopm --off \*;swaylock --indicator-thickness 7 --inside-color 00000000 --font-size 16 -fnes fill -i ~/.config/bg/lock.png' resume 'wlopm --on \*' &

# mouse
riverctl focus-follows-cursor always
riverctl hide-cursor when-typing disabled
riverctl set-cursor-warp disabled

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

for SYNAPTICS in $(riverctl list-inputs | grep -i Synaptics)
do

  riverctl input $SYNAPTICS events enabled
  riverctl input $SYNAPTICS tap enabled
  riverctl input $SYNAPTICS natural-scroll enabled

done

for POINTERS in $(riverctl list-inputs | grep -i pointer)
do

  riverctl input $POINTERS disable-while-typing disabled
  riverctl input $POINTERS accel-profile flat
  riverctl input $POINTERS pointer-accel 0

done

# general
rivertile -view-padding 3 -outer-padding 2 -main-ratio 0.5 &
riverctl border-width 2
riverctl background-color 0x000000
riverctl border-color-unfocused 0x7B6E63
riverctl border-color-focused 0x98971A

riverctl default-attach-mode bottom
riverctl default-layout rivertile

# float rule
riverctl rule-add -title "Volume Control" float
riverctl rule-add -title "LibreWolf - Sharing Indicator" float
riverctl rule-add -title "Firefox - Sharing Indicator" float
riverctl rule-add -title "Welcome to Audacity!" float
riverctl rule-add -title "Welcome to Tenacity!" float
riverctl rule-add -title "Open File" float
riverctl rule-add -title "Confirm File Replacing" float

riverctl rule-add -app-id "sober_services" float

# fix border rule
riverctl rule-add -title "Volume Control" ssd
riverctl rule-add -title "osu!" ssd
riverctl rule-add -title "Transmission" ssd
riverctl rule-add -title "Mozilla Thunderbird" ssd
riverctl rule-add -title "Betterbird" ssd
riverctl rule-add -title "org.pwmt.zathura" ssd
riverctl rule-add -title "*.pdf" ssd
riverctl rule-add -title "Open File" ssd
riverctl rule-add -title "File Upload" ssd
riverctl rule-add -title "GIMP Startup" ssd
riverctl rule-add -title "LibreOffice" ssd
riverctl rule-add -title "Save Document?" ssd
riverctl rule-add -title "Open" ssd
riverctl rule-add -title "Save" ssd
riverctl rule-add -title "Lutris" ssd
riverctl rule-add -title "Add games to Lutris" ssd
riverctl rule-add -title "Lutris settings" ssd

riverctl rule-add -app-id "firefox" ssd
riverctl rule-add -app-id "librewolf" ssd
riverctl rule-add -app-id "audacity" ssd
riverctl rule-add -app-id "pcmanfm" ssd
riverctl rule-add -app-id "sober_services" ssd
riverctl rule-add -app-id "nwg-look" ssd
riverctl rule-add -app-id "tlpui" ssd
riverctl rule-add -app-id "xarchiver" ssd
riverctl rule-add -app-id "thunar" ssd
riverctl rule-add -app-id "imv" ssd
riverctl rule-add -app-id "tenacity" ssd

# apps binds
riverctl map normal Super Return spawn \
	'foot'

riverctl map normal Super R spawn \
	'foot -e lf'

riverctl map normal Super S spawn \
	'foot -e ncmpcpp -q'

riverctl map normal Super A spawn \
	'foot -e newsboat -q'

riverctl map normal Super D spawn \
	'tofi-drun'

riverctl map normal Super E spawn \
	'thunderbird'

riverctl map normal Super W spawn \
	'firefox'

# camera
riverctl map normal Super+Control C spawn \
	'ffplay -loglevel -8 -fast /dev/video0'

riverctl rule-add -app-id "ffplay" float

# lockscreen
riverctl map normal Super Comma spawn \
	'swaylock --indicator-thickness 7 --inside-color 00000000 --font-size 16 -nes fill -i ~/.config/bg/lock.png'

# notification details without bars
riverctl map normal Super B spawn \
	'notify-send -t 2000 "`date +%A` `date +%m/%d/%Y`" "`date +%H:%M:%S`"'

riverctl map normal Super+Shift B spawn \
	'notify-send -t 2000 "`acpi -b`"'

riverctl map normal Super+Control B spawn \
	'notify-send -t 2000 "`acpi -t`"'

riverctl map normal Super Space spawn \
	'dunstctl history-pop'

# color-picker
riverctl map normal Super P spawn \
	'wl-color-picker clipboard'

# screenshot
riverctl map normal None Print spawn \
	'IMG=$HOME/stuffs/pic/screenshots/$(date +%m-%d-%Y_%T)-screenshot.png && grim -g "$(slurp)" $IMG && notify-send -t 1250 "screenshot taken"'

riverctl map normal Control Print spawn \
	'IMG=$HOME/stuffs/pic/screenshots/$(date +%m-%d-%Y_%T)-screenshot.png && grim -c $IMG && notify-send -t 1250 "screenshot taken"'

# close, exit and reload river
riverctl map normal Super Q \
	close

riverctl map normal Super+Shift Q \
	exit

riverctl map normal Super+Shift R spawn \
	~/.config/river/init

# focus window
riverctl map normal Super H focus-view \
	left

riverctl map normal Super J focus-view \
	down

riverctl map normal Super K focus-view \
	up

riverctl map normal Super L focus-view \
	right

# move/resize window
riverctl map normal Super Left send-layout-cmd \
	rivertile 'main-ratio -0.01'

riverctl map normal Super Right send-layout-cmd \
	rivertile 'main-ratio +0.01'

riverctl map normal Super+Control Left \
	move left 50

riverctl map normal Super+Control Down \
	move down 50

riverctl map normal Super+Control Up \
	move up 50

riverctl map normal Super+Control Right \
	move right 50

riverctl map normal Super+Shift Left \
	resize horizontal -50

riverctl map normal Super+Shift Down \
	resize vertical -50

riverctl map normal Super+Shift Up \
	resize vertical 50

riverctl map normal Super+Shift Right \
	resize horizontal 50

# workspaces
for i in $(seq 1 9)
do
    
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags

done

# fullscreen/float
riverctl map normal Super F \
	toggle-fullscreen

riverctl map normal Super+Shift F \
	toggle-float

# media binds
riverctl map normal None XF86Eject spawn \
	'eject -T'

riverctl map normal None XF86AudioRaiseVolume spawn \
	'wpctl set-volume -l 2.0 @DEFAULT_SINK@ 5%+'

riverctl map normal None XF86AudioLowerVolume spawn \
	'wpctl set-volume -l 2.0 @DEFAULT_SINK@ 5%-'

riverctl map normal None XF86AudioMute spawn \
	'wpctl set-mute @DEFAULT_SINK@ toggle'

riverctl map normal None XF86AudioMicMute spawn \
	'pactl set-source-mute @DEFAULT_SOURCE@ toggle'

riverctl map normal None XF86AudioMedia spawn \
	'playerctl play-pause'

riverctl map normal None XF86AudioPlay spawn \
	'playerctl play-pause'

riverctl map normal None XF86AudioPrev spawn \
	'playerctl previous'

riverctl map normal None XF86AudioNext spawn \
	'playerctl next'

riverctl map normal None XF86MonBrightnessUp spawn \
	'brightnessctl set 10%+'

riverctl map normal None XF86MonBrightnessDown spawn \
	'brightnessctl set 10%-'
