#!/bin/sh

# autostart
pkill -9 waybar && pkill -9 dunst && pkill -9 wlsunset && pkill -9 polkit-mate-authentication-agent-1
waybar &
dunst &
wlsunset -t 2300 -S 0:00 &
/usr/libexec/polkit-mate-authentication-agent-1 &

#wlr-randr --output eDP-1 --custom-mode 1024x768 @60Hz
wlr-randr --output DP-1 --preferred

# apps binds
riverctl map normal Super Return spawn "foot"
riverctl map normal Super R spawn "foot -e ranger"
riverctl map normal Super D spawn "tofi-drun -c ~/.config/tofi/config"
riverctl map normal Super E spawn "thunderbird"
riverctl map normal Super W spawn "librewolf"

# swaylock with lid close
riverctl map-switch normal lid open spawn "swaylock -elc 000000"
riverctl map normal Super Comma spawn "swaylock -elc 000000"

# notification details without bars
riverctl map normal Super B spawn 'notify-send -t 2000 "`date +%A` `date +%m/%d/%Y`" "`date +%H:%M:%S`"'
riverctl map normal Super+Shift B spawn 'notify-send -t 2000 "`acpi -b`"'
riverctl map normal Super+Control B spawn 'notify-send -t 2000 "`acpi -t`"'

# screenshot
riverctl map normal None Print spawn 'IMG=~/stuffs/pic/screenshots/$(date | sed "s/\s/-/g" | sed "s/--/-/g").png && grim -g "$(slurp)" $IMG && cat $IMG | wl-copy && notify-send "screenshot taken" -t 1250'
riverctl map normal Control Print spawn 'IMG=~/stuffs/pic/screenshots/$(date | sed "s/\s/-/g" | sed "s/--/-/g").png && grim $IMG && cat $IMG | wl-copy && notify-send "screenshot taken" -t 1250'

# reload river
riverctl map normal Super+Shift Escape spawn ~/.config/river/init

# close, exit river
riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit

# focus window
riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right

# move window
riverctl map normal Super Left send-layout-cmd rivertile "main-ratio -0.01"
riverctl map normal Super Right send-layout-cmd rivertile "main-ratio +0.01"

# tags/workspaces
for i in $(seq 1 9)
do
    
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags

done

# fullscreen
riverctl map normal Super F toggle-fullscreen

# media binds
for mode in normal locked
do
    riverctl map $mode None XF86Eject spawn 'eject -T'

    riverctl map $mode None XF86AudioRaiseVolume spawn 'wpctl set-volume -l 2.0 @DEFAULT_SINK@ 5%+'
    riverctl map $mode None XF86AudioLowerVolume spawn 'wpctl set-volume -l 2.0 @DEFAULT_SINK@ 5%-'
    riverctl map $mode None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
    riverctl map $mode None XF86AudioMicMute spawn 'pactl set-source-mute @DEFAULT_SOURCE@ toggle'

    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext spawn 'playerctl next'

    riverctl map $mode None XF86MonBrightnessUp spawn 'brightnessctl set +10%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 10%-'

done

# border and background color
riverctl background-color 0x000000
riverctl border-color-unfocused 0x7b6e63
riverctl border-color-focused 0x98971a
riverctl border-width 2

# mouse
riverctl focus-follows-cursor always
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp disabled

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for TOUCHPAD in $(riverctl list-inputs | grep -i touchpad )
do

  riverctl input $TOUCHPAD events enabled
  riverctl input $TOUCHPAD tap enabled
  riverctl input $TOUCHPAD natural-scroll enabled

done

for POINTERS in $(riverctl list-inputs)
do

  riverctl input $POINTERS accel-profile flat
  riverctl input $POINTERS pointer-accel 0.3

done

# tty-like keyboard config
riverctl set-repeat 50 300

# master layout and gaps
riverctl default-attach-mode bottom
riverctl default-layout rivertile
rivertile -view-padding 3 -outer-padding 2 -main-ratio 0.5 &

# float rule
riverctl rule-add -title "Volume Control" float
