#!/bin/sh

# autokill & start
pkill -9 swayidle && pkill -9 waybar && pkill -9 dunst && pkill -9 wlsunset && pkill -9 polkit-mate-authentication-agent-1

waybar &
dunst &
wlsunset -t 2300 -S 0:00 &
/usr/libexec/polkit-mate-authentication-agent-1 &

# resolution
#wlr-randr --output eDP-1 --custom-mode 1024x768 @60Hz
wlr-randr --output DP-1 --preferred

# xorg-like idle
swayidle -w \
  timeout 600 'swaylock -ec 000000' &

# apps binds
riverctl map normal Super Return spawn \
	"foot"

riverctl map normal Super R spawn \
	"foot -e ranger"

riverctl map normal Super D spawn \
	"tofi-drun"

riverctl map normal Super E spawn \
	"thunderbird"

riverctl map normal Super W spawn \
	"librewolf"

# camera
riverctl map normal Super+Control C spawn \
	"ffplay -fast /dev/video0"

riverctl rule-add -app-id "ffplay" float

# lockscreen
riverctl map-switch normal lid open spawn \
	"swaylock -ec 000000"

riverctl map normal Super Comma spawn \
	"swaylock -ec 000000"

# notification details without bars
riverctl map normal Super B spawn \
	'notify-send -t 2000 "`date +%A` `date +%m/%d/%Y`" "`date +%H:%M:%S`"'

riverctl map normal Super+Shift B spawn \
	'notify-send -t 2000 "`acpi -b`"'

riverctl map normal Super+Control B spawn \
	'notify-send -t 2000 "`acpi -t`"'

riverctl map normal Super Space spawn \
	"dunstctl history-pop"

# screenshot
riverctl map normal None Print spawn \
	'IMG=~/stuffs/pic/screenshots/$(date +%m-%d-%Y_%T)-screenshot.png && grim -g "$(slurp)" $IMG && notify-send -t 1250 "screenshot taken"'

riverctl map normal Control Print spawn \
	'IMG=~/stuffs/pic/screenshots/$(date +%m-%d-%Y_%T)-screenshot.png && grim $IMG && notify-send -t 1250 "screenshot taken"'

# close, exit and reload river
riverctl map normal Super Q \
	close

riverctl map normal Super+Shift Q \
	exit

riverctl map normal Super+Shift R spawn \
	~/.config/river/init

# focus window
riverctl map normal Super H focus-view \
	left

riverctl map normal Super J focus-view \
	down

riverctl map normal Super K focus-view \
	up

riverctl map normal Super L focus-view \
	right

# move window
riverctl map normal Super Left send-layout-cmd \
	rivertile "main-ratio -0.01"

riverctl map normal Super Right send-layout-cmd \
	rivertile "main-ratio +0.01"

# workspaces
for i in $(seq 1 9)
do
    
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i \
	set-focused-tags $tags
    riverctl map normal Super+Shift $i \
	set-view-tags $tags

done

# fullscreen
riverctl map normal Super F \
	toggle-fullscreen

# media binds
riverctl map normal None XF86Eject spawn \
	'eject -T'

riverctl map normal None XF86AudioRaiseVolume spawn \
	'wpctl set-volume -l 2.0 @DEFAULT_SINK@ 5%+'

riverctl map normal None XF86AudioLowerVolume spawn \
	'wpctl set-volume -l 2.0 @DEFAULT_SINK@ 5%-'

riverctl map normal None XF86AudioMute spawn \
	'wpctl set-mute @DEFAULT_SINK@ toggle'

riverctl map normal None XF86AudioMicMute spawn \
	'pactl set-source-mute @DEFAULT_SOURCE@ toggle'

riverctl map normal None XF86AudioMedia spawn \
	'playerctl play-pause'

riverctl map normal None XF86AudioPlay spawn \
	'playerctl play-pause'

riverctl map normal None XF86AudioPrev spawn \
	'playerctl previous'

riverctl map normal None XF86AudioNext spawn \
	'playerctl next'

riverctl map normal None XF86MonBrightnessUp spawn \
	'brightnessctl set 10%+'

riverctl map normal None XF86MonBrightnessDown spawn \
	'brightnessctl set 10%-'

# border and background color
riverctl background-color 0x000000
riverctl border-color-unfocused 0x7b6e63
riverctl border-color-focused 0x98971a
riverctl border-width 2

# mouse
riverctl focus-follows-cursor always
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp disabled

riverctl map-pointer normal Super BTN_LEFT \
	move-view

riverctl map-pointer normal Super BTN_RIGHT \
	resize-view

for SYNAPTICS in $(riverctl list-inputs | grep -i Synaptics)
do

  riverctl input $SYNAPTICS events enabled
  riverctl input $SYNAPTICS tap enabled
  riverctl input $SYNAPTICS natural-scroll enabled

done

for POINTERS in $(riverctl list-inputs | grep -i pointer)
do

  riverctl input $POINTERS accel-profile flat
  riverctl input $POINTERS pointer-accel 0.3

done

# tty-like keyboard config
riverctl set-repeat 50 300

# master layout and gaps
riverctl default-attach-mode bottom
riverctl default-layout rivertile
rivertile -view-padding 3 -outer-padding 2 -main-ratio 0.5 &

# float rule
riverctl rule-add -title "Volume Control" float
riverctl rule-add -title "LibreWolf - Sharing Indicator" float
riverctl rule-add -title "Firefox - Sharing Indicator" float

# fix border rule
riverctl rule-add -title "Volume Control" ssd
riverctl rule-add -title "LibreWolf" ssd
riverctl rule-add -title "LibreWolf - Sharing Indicator" ssd
riverctl rule-add -title "Firefox" ssd
riverctl rule-add -title "Firefox - Sharing Indicator" ssd
