[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#3c3836'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#ebdbb2'

[colors.bright]
black   = '#7c6f64'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#fbf1c7'
