#!/bin/sh

# start polybar
$HOME/.config/polybar/launch.sh &

# lockscreen with suspend
xss-lock --transfer-sleep-lock -- i3lock --nofork -ec 00000000 &

# resolution
#xrandr --output eDP1 --mode 1024x768
xrandr --output DP1 --preferred

# tty-like keyboard rate
xset r rate 300 50

# general
bspc monitor -d 1 2 3 4 5 6 7 8 9 &
bspc config window_gap 5
bspc config border_width 2
bspc config normal_border_color "#7B6E63"
bspc config focused_border_color "#458588"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bsp-layout set tall 1 -- --master-size 0.5
bsp-layout set tall 2 -- --master-size 0.5
bsp-layout set tall 3 -- --master-size 0.5
bsp-layout set tall 4 -- --master-size 0.5
bsp-layout set tall 5 -- --master-size 0.5
bsp-layout set tall 6 -- --master-size 0.5
bsp-layout set tall 7 -- --master-size 0.5
bsp-layout set tall 8 -- --master-size 0.5
bsp-layout set tall 9 -- --master-size 0.5

bspc rule -a pavucontrol state=floating
