#!/bin/sh

# start polybar
$HOME/.config/polybar/launch.sh &

xss-lock --transfer-sleep-lock -- i3lock --nofork -ec 00000000 &

#xrandr --output eDP1 --mode 1024x768
xrandr --output DP1 --preferred

# general
bspc monitor -d 1 2 3 4 5 6 7 8 9 &
bspc config window_gap 5
bspc config border_width 2
bspc config normal_border_color "#7B6E63"
bspc config focused_border_color "#458588"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a pavucontrol state=floating
