#!/bin/sh

# use neovim for vim if present
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# colored outputs
alias \
	ls='ls -hN --color=auto --group-directories-first' \
	grep='grep --color=auto' \
	diff='diff --color=auto' \
	ccat='highlight --out-format=ansi' \
	ip='ip -color=auto'

# verbose outputs
alias \
	cp='cp -riv' \
	mv='mv -iv' \
	rm='rm -Irv' \
	bc='bc -ql' \
	rsync='rsync -Pvrlu' \
	mkdir='mkdir -pv' \
	ffmpeg='ffmpeg -hide_banner'

# shortcuts/abbreviations
alias \
	ff='fastfetch --logo void2_small --logo-color-2 37 --logo-padding-left 2 --logo-padding-right 2 --logo-padding-top 1' \
	xr='doas xbps-remove -Rov' \
	xi='doas xbps-install -v' \
	xu='doas xbps-install -Suv && xcheckrestart -v' \
	xq='xbps-query -Rs' \
	xf='xbps-query -f' \
	xc='doas xbps-remove -Ov' \
	lf='lfub' \
	fstrim='doas fstrim -av' \
	yt-dla='cd $HOME/stuffs/dls/yt-aud/ && yt-dlp -x --restrict-filenames -o "%(title)s.%(ext)s" --sponsorblock-remove all --audio-format mp3' \
	yt-dlv='cd $HOME/stuffs/dls/yt-vid/ && yt-dlp -S res:1080 -S vcodec:h264 --restrict-filenames -o "%(title)s.%(ext)s" --sponsorblock-remove all --audio-format mp3 --write-sub --write-auto-sub --sub-lang "en.*"' \
	reboot='loginctl reboot' \
	poweroff='loginctl poweroff' \
	reload='loginctl reload' \
	suspend='loginctl suspend' \
	hibernate='loginctl hibernate' \
	hybrid-sleep='loginctl hybrid-sleep' \
	suspend-then-hibernate='loginctl suspend-then-hibernate' \
	bctl='bluetoothctl' \
	sudo='doas' \
	update-mdocml='doas makewhatis -a' \
	update-grub='doas update-grub'

# xbps-src
alias \
	xb='cd $HOME/stuffs/git/xbps-src/ && doas xbps-install -v --repository hostdir/binpkgs' \
	xbn='cd $HOME/stuffs/git/xbps-src/ && doas xbps-install -v --repository hostdir/binpkgs/nonfree' \
	xbps-src='$HOME/stuffs/git/xbps-src/xbps-src' \
	xbps-src-update='cd $HOME/stuffs/git/xbps-src && git pull'
